apiVersion: v1
kind: PersistentVolume
metadata:
  name: busybox-volume
  namespace: busybox
  labels:
    app: busybox
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /nvme/k8s-persistence-storage/busybox #can use local, S3, EFS, etc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-volume-claim
  namespace: busybox
  labels:
    app: busybox
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
